export const nftModul = [
  {
    id: "0001",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 1,
    verified: false,
  },
  {
    id: "0002",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 4,
    verified: true,
  },
  {
    id: "0003",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 0,
    verified: false,
  },
  {
    id: "0004",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 3,
    verified: true,
  },
  {
    id: "0005",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 1,
    verified: false,
  },
  {
    id: "0006",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 4,
    verified: true,
  },
  {
    id: "0007",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 0,
    verified: false,
  },
  {
    id: "0008",
    icon: "/images/icons/rexHead.png",
    image: "/images/nft/nft-1.jpg",
    name: "Small Arms Syndicate",
    likes: 3,
    verified: true,
  },
];
